copied and edited existing script to run the training function
dotdecimal/astroid-script-library pull request #25
Opened 2019-05-15 17:24 UTC by camiloamontoya

created post_calc_request_generic_camilo_edit to run the function that was created in AST-Camilo_Api_Demo and edited the thinknode config file to work with my realm

2019-05-16 18:47 UTC, danielpatenaude requested changes
Rename this PR to include the [AST-XXX] prefix.

2019-05-16 19:26 UTC, camiloamontoya commented
included the requested prefix [AST - 3122]

2019-05-16 19:35 UTC, danielpatenaude approved these changes

2019-07-31 17:05 UTC, danielpatenaude commented
Closing training PR

2019-07-31 17:05 UTC, closed without merging